/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Model.room;

import DBconfig.Connect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author amerm
 */
public class Bill_RoomRec extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    /**
     * Creates new form Bill_RoomRec
     */
    public Bill_RoomRec() {
        initComponents();
        conn = Connect.ConnectDB();
        setLocationRelativeTo(null);
        Get_Data();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Billing Records");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Bill No.", "Patient Id", "Patient Name", "Gender", "Blood Group", "Disease", "Admit Date", "Room No.", "Doctor Id", "Doctor Name", "Discharge Date", "Room Charges", "Service Name", "Service Charges", "Billing Date", "Payment Method", "Payment Method Details", "Total Room Charges", "No. Of Days", "Total Charges"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1670, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Get_Data(){
        try{
            String sql="Select BillNo as 'Bill No.',PatientRegistration.PatientID as 'Patient ID',"
                    + "PatientRegistration.PatientName as 'Patient Name',PatientRegistration.Gen as 'Gender',"
                    + "PatientRegistration.BG as 'Blood Group',Disease as 'Disease',AdmitDate as 'Admit Date',Room.RoomNo as "
                    + "'Room No',Doctor.DoctorID as 'Doctor ID',DoctorName as 'Doctor Name',DischargeDate as "
                    + "'Discharge Date',Bill_Room.RoomCharges as 'Room Charges',Services.ServiceName as 'Service Name', Bill_Room.ServiceCharges as 'Service Charges',"
                    + "Bill_Room.BillingDate as 'Billing Date',PaymentMethod as 'Payment Method',"
                    + "PaymentMethodDetails as 'Payment Method Details',TotalRoomCharges as 'Total Room Charges',"
                    + "NoOfDays as 'No. Of Days', TotalCharges as 'Total Charges' from "
                    + "Room,Doctor,PatientRegistration,AdmitPatient_Room,DischargePatient_Room,Bill_Room,Services "
                    + "where Room.RoomNo=AdmitPatient_Room.RoomNo and Doctor.DoctorID=AdmitPatient_Room.DoctorID "
                    + "and PatientRegistration.PatientID=AdmitPatient_Room.PatientID  and "
                    + "AdmitPatient_Room.PatientID= DischargePatient_Room.admitID and PatientRegistration.PatientID=Services.PatientID and "
                    + "Bill_Room.DischargeID=DischargePatient_Room.AdmitID  order by Billingdate";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
      
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        try{
            conn = Connect.ConnectDB();
            int row= jTable1.getSelectedRow();
            this.setVisible(false);
            Bill_Room frm = new Bill_Room();
            frm.setVisible(true);
            String add= jTable1.getModel().getValueAt(row, 0).toString();
            frm.txtBillNo.setText(add);
            String add1= jTable1.getModel().getValueAt(row, 1).toString();
            frm.PatientID.setText(add1);
            String add2= jTable1.getModel().getValueAt(row, 2).toString();
            frm.txtPatientName.setText(add2);
            String add3= jTable1.getModel().getValueAt(row, 3).toString();
            frm.txtGender.setText(add3);
            String add4= jTable1.getModel().getValueAt(row, 4).toString();
            frm.txtBloodGroup.setText(add4);
            String add5= jTable1.getModel().getValueAt(row, 5).toString();
            frm.txtDisease.setText(add5);
            String add6= jTable1.getModel().getValueAt(row, 6).toString();
            frm.txtAdmitDate.setText(add6);
            String add7= jTable1.getModel().getValueAt(row, 7).toString();
            frm.txtRoomNo.setText(add7);
            String add8= jTable1.getModel().getValueAt(row, 8).toString();
            frm.txtDoctorID.setText(add8);
            String add9= jTable1.getModel().getValueAt(row, 9).toString();
            frm.txtDoctorName.setText(add9);
            String add10= jTable1.getModel().getValueAt(row, 10).toString();
            frm.txtDischargeDate.setText(add10);
            String add11= jTable1.getModel().getValueAt(row, 11).toString();
            frm.txtRoomCharges.setText(add11);
            String add12= jTable1.getModel().getValueAt(row, 12).toString();
            frm.txtServiceName.setText(add12);
            String add13= jTable1.getModel().getValueAt(row, 13).toString();
            frm.txtServiceCharges.setText(add13);
            String add14= jTable1.getModel().getValueAt(row, 14).toString();
            frm.txtBillingDate.setText(add14);
            String add15= jTable1.getModel().getValueAt(row, 15).toString();
            frm.cmbPaymentMethod.setSelectedItem(add15);
            String add16= jTable1.getModel().getValueAt(row, 16).toString();
            frm.txtPaymentMethodDetails.setText(add16);
            String add17= jTable1.getModel().getValueAt(row, 17).toString();
            frm.txtTotalRoomCharges.setText(add17);
            String add18= jTable1.getModel().getValueAt(row, 18).toString();
            frm.txtNoOfDays.setText(add18);
            String add19= jTable1.getModel().getValueAt(row, 19).toString();
            frm.txtTotalCharges.setText(add19);
            frm.btnUpdate.setEnabled(true);
            frm.btnDelete.setEnabled(true);
            frm.btnSave.setEnabled(false);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bill_RoomRec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bill_RoomRec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bill_RoomRec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bill_RoomRec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bill_RoomRec().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
